// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 添​加
		 */
		add: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 重​置
		 */
		reset: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 确​定
		 */
		confirm: string
		/**
		 * 上​移
		 */
		moveUp: string
		/**
		 * 下​移
		 */
		moveDown: string
	}
	settings: {
		general: {
			/**
			 * 通​用
			 */
			name: string
			/**
			 * 开​关​、​文​本​与​下​拉​等​基​础​控​件​示​例
			 */
			desc: string
			enableFeature: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 总​开​关​；​关​闭​后​下​方​「​详​细​日​志​」​会​隐​藏
				 */
				desc: string
			}
			greeting: {
				/**
				 * 问​候​语
				 */
				name: string
				/**
				 * 单​行​文​本​，​演​示​ ​v​a​l​i​d​a​t​e​（​非​空​且​不​超​过​ ​2​0​ ​字​）
				 */
				desc: string
				/**
				 * 问​候​语​不​能​为​空​且​不​超​过​ ​2​0​ ​个​字​符
				 */
				invalid: string
			}
			mode: {
				/**
				 * 模​式
				 */
				name: string
				/**
				 * 下​拉​选​择​，​取​值​受​ ​o​p​t​i​o​n​s​ ​约​束
				 */
				desc: string
				/**
				 * 简​单
				 */
				simple: string
				/**
				 * 高​级
				 */
				advanced: string
			}
			verboseLog: {
				/**
				 * 详​细​日​志
				 */
				name: string
				/**
				 * 仅​当​「​启​用​功​能​」​开​启​时​可​见​，​演​示​ ​v​i​s​i​b​l​e​ ​联​动
				 */
				desc: string
			}
		}
		appearance: {
			/**
			 * 外​观
			 */
			name: string
			/**
			 * 颜​色​、​滑​块​与​数​字​控​件​示​例
			 */
			desc: string
			accentColor: {
				/**
				 * 强​调​色
				 */
				name: string
				/**
				 * 颜​色​控​件​，​存​储​为​十​六​进​制​色​值
				 */
				desc: string
			}
			fontScale: {
				/**
				 * 字​号​缩​放
				 */
				name: string
				/**
				 * 滑​块​，​通​过​ ​d​i​s​p​l​a​y​F​o​r​m​a​t​ ​以​百​分​比​显​示
				 */
				desc: string
			}
			maxItems: {
				/**
				 * 最​大​条​目​数
				 */
				name: string
				/**
				 * 数​字​控​件​，​限​定​ ​m​i​n​ ​/​ ​m​a​x​ ​/​ ​s​t​e​p
				 */
				desc: string
			}
		}
		paths: {
			/**
			 * 路​径
			 */
			name: string
			/**
			 * 文​件​、​文​件​夹​与​多​行​文​本​控​件​示​例
			 */
			desc: string
			templateFile: {
				/**
				 * 模​板​文​件
				 */
				name: string
				/**
				 * 文​件​路​径​，​带​联​想​选​择​器​（​仅​联​想​ ​M​a​r​k​d​o​w​n​ ​文​件​）
				 */
				desc: string
			}
			outputFolder: {
				/**
				 * 输​出​文​件​夹
				 */
				name: string
				/**
				 * 文​件​夹​路​径​，​带​联​想​选​择​器
				 */
				desc: string
			}
			header: {
				/**
				 * 页​首​文​本
				 */
				name: string
				/**
				 * 多​行​文​本​框
				 */
				desc: string
			}
		}
		advanced: {
			/**
			 * 进​阶
			 */
			name: string
			/**
			 * 原​生​列​表​、​动​作​按​钮​与​ ​R​e​a​c​t​ ​孤​岛​示​例
			 */
			desc: string
			bookmarks: {
				/**
				 * 书​签
				 */
				name: string
				/**
				 * 原​生​ ​l​i​s​t​：​可​增​删​、​拖​拽​排​序​，​编​辑​走​对​话​框
				 */
				desc: string
				/**
				 * 添​加​书​签
				 */
				add: string
				/**
				 * 暂​无​书​签​，​点​击​右​上​角​「​+​」​添​加
				 */
				empty: string
				/**
				 * 新​书​签​ ​{​i​n​d​e​x​}
				 * @param {unknown} index
				 */
				defaultName: RequiredParams<'index'>
				/**
				 * 未​设​置​路​径
				 */
				noPath: string
				/**
				 * 编​辑
				 */
				edit: string
				/**
				 * 编​辑​书​签
				 */
				editTitle: string
				/**
				 * 名​称
				 */
				namePlaceholder: string
				/**
				 * 路​径
				 */
				pathPlaceholder: string
			}
			reset: {
				/**
				 * 重​置​全​部​设​置
				 */
				name: string
				/**
				 * 把​所​有​设​置​恢​复​为​默​认​值
				 */
				desc: string
				/**
				 * 重​置
				 */
				button: string
			}
			tags: {
				/**
				 * 标​签
				 */
				name: string
				/**
				 * R​e​a​c​t​ ​孤​岛​：​组​件​自​行​订​阅​ ​S​e​t​t​i​n​g​s​S​t​o​r​e​ ​并​异​步​落​盘
				 */
				desc: string
				/**
				 * 输​入​标​签​后​回​车​添​加
				 */
				placeholder: string
				/**
				 * 暂​无​标​签
				 */
				empty: string
				/**
				 * 共​ ​{​c​o​u​n​t​}​ ​个
				 * @param {unknown} count
				 */
				count: RequiredParams<'count'>
			}
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 添加
		 */
		add: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 重置
		 */
		reset: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 确定
		 */
		confirm: () => LocalizedString
		/**
		 * 上移
		 */
		moveUp: () => LocalizedString
		/**
		 * 下移
		 */
		moveDown: () => LocalizedString
	}
	settings: {
		general: {
			/**
			 * 通用
			 */
			name: () => LocalizedString
			/**
			 * 开关、文本与下拉等基础控件示例
			 */
			desc: () => LocalizedString
			enableFeature: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 总开关；关闭后下方「详细日志」会隐藏
				 */
				desc: () => LocalizedString
			}
			greeting: {
				/**
				 * 问候语
				 */
				name: () => LocalizedString
				/**
				 * 单行文本，演示 validate（非空且不超过 20 字）
				 */
				desc: () => LocalizedString
				/**
				 * 问候语不能为空且不超过 20 个字符
				 */
				invalid: () => LocalizedString
			}
			mode: {
				/**
				 * 模式
				 */
				name: () => LocalizedString
				/**
				 * 下拉选择，取值受 options 约束
				 */
				desc: () => LocalizedString
				/**
				 * 简单
				 */
				simple: () => LocalizedString
				/**
				 * 高级
				 */
				advanced: () => LocalizedString
			}
			verboseLog: {
				/**
				 * 详细日志
				 */
				name: () => LocalizedString
				/**
				 * 仅当「启用功能」开启时可见，演示 visible 联动
				 */
				desc: () => LocalizedString
			}
		}
		appearance: {
			/**
			 * 外观
			 */
			name: () => LocalizedString
			/**
			 * 颜色、滑块与数字控件示例
			 */
			desc: () => LocalizedString
			accentColor: {
				/**
				 * 强调色
				 */
				name: () => LocalizedString
				/**
				 * 颜色控件，存储为十六进制色值
				 */
				desc: () => LocalizedString
			}
			fontScale: {
				/**
				 * 字号缩放
				 */
				name: () => LocalizedString
				/**
				 * 滑块，通过 displayFormat 以百分比显示
				 */
				desc: () => LocalizedString
			}
			maxItems: {
				/**
				 * 最大条目数
				 */
				name: () => LocalizedString
				/**
				 * 数字控件，限定 min / max / step
				 */
				desc: () => LocalizedString
			}
		}
		paths: {
			/**
			 * 路径
			 */
			name: () => LocalizedString
			/**
			 * 文件、文件夹与多行文本控件示例
			 */
			desc: () => LocalizedString
			templateFile: {
				/**
				 * 模板文件
				 */
				name: () => LocalizedString
				/**
				 * 文件路径，带联想选择器（仅联想 Markdown 文件）
				 */
				desc: () => LocalizedString
			}
			outputFolder: {
				/**
				 * 输出文件夹
				 */
				name: () => LocalizedString
				/**
				 * 文件夹路径，带联想选择器
				 */
				desc: () => LocalizedString
			}
			header: {
				/**
				 * 页首文本
				 */
				name: () => LocalizedString
				/**
				 * 多行文本框
				 */
				desc: () => LocalizedString
			}
		}
		advanced: {
			/**
			 * 进阶
			 */
			name: () => LocalizedString
			/**
			 * 原生列表、动作按钮与 React 孤岛示例
			 */
			desc: () => LocalizedString
			bookmarks: {
				/**
				 * 书签
				 */
				name: () => LocalizedString
				/**
				 * 原生 list：可增删、拖拽排序，编辑走对话框
				 */
				desc: () => LocalizedString
				/**
				 * 添加书签
				 */
				add: () => LocalizedString
				/**
				 * 暂无书签，点击右上角「+」添加
				 */
				empty: () => LocalizedString
				/**
				 * 新书签 {index}
				 */
				defaultName: (arg: { index: unknown }) => LocalizedString
				/**
				 * 未设置路径
				 */
				noPath: () => LocalizedString
				/**
				 * 编辑
				 */
				edit: () => LocalizedString
				/**
				 * 编辑书签
				 */
				editTitle: () => LocalizedString
				/**
				 * 名称
				 */
				namePlaceholder: () => LocalizedString
				/**
				 * 路径
				 */
				pathPlaceholder: () => LocalizedString
			}
			reset: {
				/**
				 * 重置全部设置
				 */
				name: () => LocalizedString
				/**
				 * 把所有设置恢复为默认值
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				button: () => LocalizedString
			}
			tags: {
				/**
				 * 标签
				 */
				name: () => LocalizedString
				/**
				 * React 孤岛：组件自行订阅 SettingsStore 并异步落盘
				 */
				desc: () => LocalizedString
				/**
				 * 输入标签后回车添加
				 */
				placeholder: () => LocalizedString
				/**
				 * 暂无标签
				 */
				empty: () => LocalizedString
				/**
				 * 共 {count} 个
				 */
				count: (arg: { count: unknown }) => LocalizedString
			}
		}
	}
}

export type Formatters = {}
