// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * O​b​s​i​d​i​a​n​ ​p​l​u​g​i​n​ ​s​t​a​r​t​e​r
	 */
	'obsidian-plugin-starter': string
}

export type TranslationFunctions = {
	/**
	 * Obsidian plugin starter
	 */
	'obsidian-plugin-starter': () => LocalizedString
}

export type Formatters = {}
